---
services:
  hypanel:
    image: alireza7/s-ui
    container_name: hypanel
    hostname: "hypanel"
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    ports:
      - "2095:2095"
      - "2096:2096"
    networks:
      - hypanel
    entrypoint: "./entrypoint.sh"

networks:
  hypanel:
    driver: bridge
